server :
  port : 8090
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

      spring :
        datasource :
          driver-class-name: org.mariadb.jdbc.Driver
            username: root
            password: 123456
          
           jpa:
            database: h2
            database-platform: org.hibernate.dialect.H2Dialec
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 120MB

  spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.url=jdbc:mysql://localhost:3306/board